using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Warnings and announcements to human players — "Your lair is too small",
/// and later "You have no gold", "Your Dungeon Heart is under attack"…
/// Every system asks for one by ID; this decides whether, when and how it's
/// given:
///
///   Per player     each human player has their own channel (cooldowns,
///                  queue, voice). AI factions get none — announcing to one
///                  does nothing.
///   Cooldown       a warning won't repeat to a player within its cooldown,
///                  so a dozen minions without a bed make one announcement.
///   One voice      lines never overlap: while one plays, others queue,
///                  highest priority first, a short gap between lines.
///   Expiry         a queued warning still waiting after maxQueueSeconds is
///                  dropped — it's no longer news.
///   Text           shown when its line starts (at once if it has no audio).
///
/// Lines come from the Announcements workbook (Sunder > Import Announcements
/// builds an AnnouncementCatalogue in Resources, found automatically): each
/// announcement's priority and cooldown, and its lines — variants picked at
/// random by weight, with text and audio per language. Audio is matched by
/// file name, so recordings need no wiring. Any announcement the code uses
/// that the workbook hasn't got yet still works, with built-in placeholder
/// text. Text goes to the HUD footer's popup for now.
///
/// Planned: a bottom-right message feed, a log with jump-to-event for urgent
/// warnings, and separate volume channels. Callers won't change — they only
/// ever pass an ID.
///
/// Scene setup: none — GameManager2D adds one. Add it to GameManager
/// yourself to pick the language or tune delivery.
/// </summary>
public class Announcer : MonoBehaviour
{
    public enum Priority { Low, Normal, High, Critical }

    public static Announcer Instance { get; private set; }

    /// <summary>
    /// Raised whenever an announcement is given (player, id, text, where —
    /// null if it isn't about a place). The location is for the planned
    /// message log's jump-to-event.
    /// </summary>
    public static event System.Action<FactionID, string, string, Vector3?> OnAnnounced;

    [Header("Lines")]
    [Tooltip("Generated by Sunder > Import Announcements. Empty = the one in Resources.")]
    [SerializeField] private AnnouncementCatalogue catalogue;
    [Tooltip("Language code for text and audio, matching the workbook's Text_<code> columns (e.g. en).")]
    [SerializeField] private string language = "en";

    /// <summary>
    /// Every announcement the code gives, with placeholder text — used for
    /// any the workbook doesn't have yet. The importer warns about those.
    /// </summary>
    public static readonly (string id, string text, Priority priority, float cooldown)[] BuiltIn =
    {
        ("LairTooSmall",       "Your lair is too small.",                 Priority.Normal,   30f),
        ("NoLair",             "You need a lair.",                        Priority.Normal,   30f),
        ("HatcheryTooSmall",   "Your hatchery is too small.",             Priority.Normal,   30f),
        ("NoHatchery",         "You need a hatchery.",                    Priority.Normal,   30f),
        ("TreasuryFull",       "Your treasury is full.",                  Priority.Normal,   45f),
        ("NoTreasury",         "You need a treasury.",                    Priority.Normal,   45f),
        ("MinionLeaving",      "A minion is leaving your dungeon.",       Priority.High,     10f),
        ("NoGoldForTraining",  "You cannot afford to train your minions.", Priority.Normal,  60f),
        ("MinionsUnderAttack", "Your minions are under attack!",          Priority.Critical, 20f),
        ("HeartUnderAttack",   "Your Dungeon Heart is under attack!",     Priority.Critical, 20f),
    };

    [Header("Delivery")]
    [Tooltip("Seconds text stays up once shown.")]
    [SerializeField] private float textHoldSeconds = 4f;
    [Tooltip("Silence between one line and the next.")]
    [SerializeField] private float gapBetweenLines = 0.5f;
    [Tooltip("A queued warning older than this is dropped instead of played.")]
    [SerializeField] private float maxQueueSeconds = 10f;
    [Tooltip("Where text appears for now. Empty = the HUD footer's popup.")]
    [SerializeField] private HotkeyPopup popup;

    private class Pending
    {
        public AnnouncementCatalogue.Announcement Entry;
        public float    QueuedAt;
        public Vector3? Where;
    }

    /// <summary>One human player's announcements: their cooldowns, queue and voice.</summary>
    private class Channel
    {
        public FactionID   Player;
        public AudioSource Voice;
        public float       VoiceFreeAt;
        public readonly Dictionary<string, float> LastGiven = new();
        public readonly List<Pending> Queue = new();
    }

    private readonly Dictionary<FactionID, Channel> _channels = new();
    private readonly Dictionary<string, AnnouncementCatalogue.Announcement> _byId = new(System.StringComparer.OrdinalIgnoreCase);
    private string _fallbackLanguage = "en";

    // ── Unity lifecycle ────────────────────────────────────────────────

    private void Awake()
    {
        if (Instance != null && Instance != this) { Destroy(this); return; }
        Instance = this;
        LoadCatalogue();
    }

    /// <summary>The workbook's announcements, then built-in placeholders for any it lacks.</summary>
    private void LoadCatalogue()
    {
        if (catalogue == null) catalogue = Resources.Load<AnnouncementCatalogue>(AnnouncementCatalogue.ResourcePath);

        _byId.Clear();
        if (catalogue != null)
        {
            _fallbackLanguage = string.IsNullOrEmpty(catalogue.defaultLanguage) ? "en" : catalogue.defaultLanguage;
            foreach (var a in catalogue.announcements)
                if (a != null && !string.IsNullOrEmpty(a.id)) _byId[a.id] = a;
        }

        foreach (var (id, text, priority, cooldown) in BuiltIn)
        {
            if (_byId.ContainsKey(id)) continue;
            var line = new AnnouncementCatalogue.Line();
            line.texts.Add(new AnnouncementCatalogue.LocalText { language = _fallbackLanguage, text = text });
            var a = new AnnouncementCatalogue.Announcement { id = id, priority = priority, cooldown = cooldown };
            a.lines.Add(line);
            _byId[id] = a;
        }
    }

    private void OnDestroy()
    {
        if (Instance == this) Instance = null;
    }

    private void Update()
    {
        foreach (var channel in _channels.Values) Pump(channel);
    }

    // ── Players ────────────────────────────────────────────────────────

    /// <summary>Gives each human player a channel; AI factions get none. Called by GameManager2D on load.</summary>
    public void SetHumanPlayers(IEnumerable<FactionID> players)
    {
        foreach (var c in _channels.Values) if (c.Voice != null) Destroy(c.Voice.gameObject);
        _channels.Clear();

        foreach (var player in players)
        {
            if (_channels.ContainsKey(player)) continue;
            var voice = new GameObject($"Voice_{player}").AddComponent<AudioSource>();
            voice.transform.SetParent(transform, false);
            voice.playOnAwake = false;
            _channels[player] = new Channel { Player = player, Voice = voice };
        }
    }

    // ── Announcing ─────────────────────────────────────────────────────

    /// <summary>Gives a warning to a faction's player, if it's human. Safe to call for anyone, any time.</summary>
    public static void Announce(FactionID faction, string id) => Instance?.Give(faction, id, null);

    /// <summary>As Announce, for something happening at a place (an attack, a full room).</summary>
    public static void Announce(FactionID faction, string id, Vector3 where) => Instance?.Give(faction, id, where);

    private void Give(FactionID faction, string id, Vector3? where)
    {
        if (!_channels.TryGetValue(faction, out var channel)) return;   // AI, or not a player
        if (!_byId.TryGetValue(id, out var entry))
        {
            Debug.LogWarning($"[Announcer] No announcement with id '{id}' in the catalogue.");
            return;
        }

        float now = Time.unscaledTime;
        if (channel.LastGiven.TryGetValue(id, out float at) && now - at < entry.cooldown) return;
        if (channel.Queue.Exists(p => p.Entry == entry)) return;
        channel.LastGiven[id] = now;

        channel.Queue.Add(new Pending { Entry = entry, QueuedAt = now, Where = where });
        // Highest priority first; oldest first within a priority.
        channel.Queue.Sort((a, b) => a.Entry.priority != b.Entry.priority
            ? b.Entry.priority.CompareTo(a.Entry.priority)
            : a.QueuedAt.CompareTo(b.QueuedAt));
        Pump(channel);
    }

    /// <summary>Starts the next queued line once the voice is free, dropping any that went stale.</summary>
    private void Pump(Channel channel)
    {
        float now = Time.unscaledTime;
        channel.Queue.RemoveAll(p => now - p.QueuedAt > maxQueueSeconds);
        if (channel.Queue.Count == 0 || now < channel.VoiceFreeAt) return;

        var next = channel.Queue[0];
        channel.Queue.RemoveAt(0);

        // One line by weight — its text and audio in the chosen language.
        var line = next.Entry.Pick(Random.value);
        string text = line?.TextFor(language, _fallbackLanguage) ?? next.Entry.id;
        var    clip = line?.ClipFor(language, _fallbackLanguage);

        if (clip != null && channel.Voice != null)
        {
            channel.Voice.PlayOneShot(clip);
            channel.VoiceFreeAt = now + clip.length + gapBetweenLines;
        }

        var target = popup != null ? popup : HudFooter.Instance != null ? HudFooter.Instance.Popup : null;
        if (target != null) target.Show($"<b>{text}</b>", textHoldSeconds);

        Debug.Log($"[Announcer] {channel.Player}: {text}");
        OnAnnounced?.Invoke(channel.Player, next.Entry.id, text, next.Where);
    }
}
